version: '3'
vars:
  BRANCH: 
    sh: git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'

tasks:
  setup: 
    silent: true

  tag-and-push:
    - git tag -d $(git tag) 
    - git tag -f {{.BRANCH}}.$(date +%y%m%d%H) 
    - git tag
