version: '3'

vars: 
  BASETAG: 0.3.0-morpheus
  TAG:
    sh: cat .image-tag

dotenv: 
  - .env

tasks:

  setup: |-
      OW=$PWD
      export ANSIBLE_CMD="$ANSIBLE_CMD -e @$OW/.devcontainer/dockerip.yml"
      # super hacky trick to get the dockerid - assuming there is only one starting with vsc-
      DOCKERID=$(docker ps | awk '/vsc-/{print $1}')
      # inspecting the image to find the real path on the host
      REAL_PWD=$(docker inspect $DOCKERID  | jq -r '.[0].Config.Labels["devcontainer.local_folder"]')
      # linking openwhisk to the home
      ln -sf $OW /home/nuvolaris/openwhisk
      # setting the tmp directory
      sudo mkdir -p $REAL_PWD
      sudo chmod 0777 $REAL_PWD
      mkdir $OW/tmp
      ln -sf $OW/tmp $REAL_PWD/tmp
      export OPENWHISK_TMP_DIR=$REAL_PWD/tmp
      ./tools/travis/setupPrereq.sh

  image-tag: echo {{.BASETAG}}.$(date +%y%m%d%H)  >.image-tag

  docker-login: >
      echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USER --password-stdin
  
  build:
   - docker build .devcontainer -t ghcr.io/nuvolaris/devow:{{.TAG}}
 
  build-and-push:
    - task: build
    - docker push ghcr.io/nuvolaris/devow:{{.TAG}}

  start: >
        docker run -d --name devow --rm
        -v $PWD:/workspaces/$(basename $PWD)
        --mount source=/var/run/docker.sock,target=/var/run/docker-host.sock,type=bind
        --network=host
        --add-host=host.docker.internal:host-gateway
        --env=REAL_HOME=$HOME
        ghcr.io/nuvolaris/devow:{{.TAG}}
  
  enter: 
        docker exec -ti --user nuvolaris devow bash
      
  stop: docker kill devow

